# Generated by Django 3.1.4 on 2020-12-24 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='expirey_date',
            new_name='expiry_date',
        ),
    ]
