# Generated by Django 3.1.4 on 2020-12-24 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20201224_0954'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='shop_id',
            new_name='shop',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='user_id',
            new_name='user',
        ),
    ]
